dist: xenial
language: cpp
compiler: clang

before_script:
- sudo apt update
- sudo apt install libboost-test-dev -y
- sudo apt install doxygen -y
- sudo apt install graphviz -y
- sudo apt-get remove --auto-remove python-enum34
- sudo apt install python3 -y
- sudo apt install python3-pip -y
- sudo apt install python3-setuptools -y
- pip3 install --upgrade pip
- pip3 install --user conan
- conan user

script:
- doxygen Doxyfile
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target package

deploy:
- provider: pages
  skip-cleanup: true
  local_dir: docs/html
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

- provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
  - curl -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujohn-jasper-doe:$BINTRAY_API_KEY "https://api.bintray.com/content/john-jasper-doe/otus-cpp/homeworks/range/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

